Exit testReplicasAndClients.sh if parallel missing
Fail fast for simpleTest if gnu parallel is not installed.

diff --git a/bftengine/tests/simpleTest/scripts/testReplicasAndClient.sh.in b/bftengine/tests/simpleTest/scripts/testReplicasAndClient.sh.in
--- a/bftengine/tests/simpleTest/scripts/testReplicasAndClient.sh.in
+++ b/bftengine/tests/simpleTest/scripts/testReplicasAndClient.sh.in
@@ -10,6 +10,11 @@ rm -f private_replica_*
 
 $toolsdir/GenerateConcordKeys -n 4 -f 1 -o private_replica_
 
+if ! [ -x "$(command -v parallel)" ]; then
+  echo 'Error: parallel is not installed.' >&2
+  exit 1
+fi
+
 parallel --halt now,fail=1 -j0 ::: \
     "$scriptdir/../server 0" \
     "$scriptdir/../server 1" \
